package helper

type StoreData struct {
	Sections struct {
		Brands            []interface{} `json:"Brands"`
		Collections       []interface{} `json:"Collections"`
		SearchSuggestions []interface{} `json:"Search Suggestions"`
		Products          []struct {
			MatchedTerms []string `json:"matched_terms"`
			Data         struct {
				ID                             string `json:"id"`
				Sku                            string `json:"sku"`
				Slug                           string `json:"slug"`
				Color                          string `json:"color"`
				Category                       string `json:"category"`
				ImageURL                       string `json:"image_url"`
				ReleaseDate                    int    `json:"release_date"`
				ProductType                    string `json:"product_type"`
				ReleaseDateYear                int    `json:"release_date_year"`
				RetailPriceCents               int    `json:"retail_price_cents"`
				RetailPriceCentsGbp            int    `json:"retail_price_cents_gbp"`
				RetailPriceCentsKrw            int    `json:"retail_price_cents_krw"`
				RetailPriceCentsSgd            int    `json:"retail_price_cents_sgd"`
				RetailPriceCentsCny            int    `json:"retail_price_cents_cny"`
				RetailPriceCentsEur            int    `json:"retail_price_cents_eur"`
				RetailPriceCentsMyr            int    `json:"retail_price_cents_myr"`
				RetailPriceCentsAud            int    `json:"retail_price_cents_aud"`
				RetailPriceCentsJpy            int    `json:"retail_price_cents_jpy"`
				RetailPriceCentsHkd            int    `json:"retail_price_cents_hkd"`
				RetailPriceCentsCad            int    `json:"retail_price_cents_cad"`
				RetailPriceCentsTwd            int    `json:"retail_price_cents_twd"`
				VariationID                    string `json:"variation_id"`
				UsedImageURL                   string `json:"used_image_url"`
				CheapestProduct                string `json:"cheapest_product"`
				ProductCondition               string `json:"product_condition"`
				LowestPriceCents               int    `json:"lowest_price_cents"`
				LowestPriceCentsHkd            int    `json:"lowest_price_cents_hkd"`
				LowestPriceCentsMyr            int    `json:"lowest_price_cents_myr"`
				LowestPriceCentsTwd            int    `json:"lowest_price_cents_twd"`
				LowestPriceCentsAud            int    `json:"lowest_price_cents_aud"`
				LowestPriceCentsSgd            int    `json:"lowest_price_cents_sgd"`
				LowestPriceCentsJpy            int    `json:"lowest_price_cents_jpy"`
				LowestPriceCentsCad            int    `json:"lowest_price_cents_cad"`
				LowestPriceCentsKrw            int    `json:"lowest_price_cents_krw"`
				LowestPriceCentsEur            int    `json:"lowest_price_cents_eur"`
				LowestPriceCentsCny            int    `json:"lowest_price_cents_cny"`
				LowestPriceCentsGbp            int    `json:"lowest_price_cents_gbp"`
				CountForProductCondition       int    `json:"count_for_product_condition"`
				InstantShipLowestPriceCents    int    `json:"instant_ship_lowest_price_cents"`
				InstantShipLowestPriceCentsGbp int    `json:"instant_ship_lowest_price_cents_gbp"`
				InstantShipLowestPriceCentsMyr int    `json:"instant_ship_lowest_price_cents_myr"`
				InstantShipLowestPriceCentsSgd int    `json:"instant_ship_lowest_price_cents_sgd"`
				InstantShipLowestPriceCentsCad int    `json:"instant_ship_lowest_price_cents_cad"`
				InstantShipLowestPriceCentsHkd int    `json:"instant_ship_lowest_price_cents_hkd"`
				InstantShipLowestPriceCentsTwd int    `json:"instant_ship_lowest_price_cents_twd"`
				InstantShipLowestPriceCentsKrw int    `json:"instant_ship_lowest_price_cents_krw"`
				InstantShipLowestPriceCentsAud int    `json:"instant_ship_lowest_price_cents_aud"`
				InstantShipLowestPriceCentsEur int    `json:"instant_ship_lowest_price_cents_eur"`
				InstantShipLowestPriceCentsJpy int    `json:"instant_ship_lowest_price_cents_jpy"`
				InstantShipLowestPriceCentsCny int    `json:"instant_ship_lowest_price_cents_cny"`
			} `json:"data"`
			Value     string `json:"value"`
			IsSlotted bool   `json:"is_slotted"`
			Labels    struct {
			} `json:"labels"`
		} `json:"Products"`
	} `json:"sections"`
	ResultID string `json:"result_id"`
	Request  struct {
		NumResultsProducts int    `json:"num_results_Products"`
		Term               string `json:"term"`
		Features           struct {
			QueryItems                     bool `json:"query_items"`
			AATest                         bool `json:"a_a_test"`
			AutoGeneratedRefinedQueryRules bool `json:"auto_generated_refined_query_rules"`
			ManualSearchandizing           bool `json:"manual_searchandizing"`
			Personalization                bool `json:"personalization"`
			FilterItems                    bool `json:"filter_items"`
			UseRerankerServiceForSearch    bool `json:"use_reranker_service_for_search"`
			UseRerankerServiceForBrowse    bool `json:"use_reranker_service_for_browse"`
			UseRerankerServiceForAll       bool `json:"use_reranker_service_for_all"`
			CustomAutosuggestUI            bool `json:"custom_autosuggest_ui"`
		} `json:"features"`
		FeatureVariants struct {
			QueryItems                     string      `json:"query_items"`
			AATest                         interface{} `json:"a_a_test"`
			AutoGeneratedRefinedQueryRules string      `json:"auto_generated_refined_query_rules"`
			ManualSearchandizing           interface{} `json:"manual_searchandizing"`
			Personalization                string      `json:"personalization"`
			FilterItems                    string      `json:"filter_items"`
			UseRerankerServiceForSearch    interface{} `json:"use_reranker_service_for_search"`
			UseRerankerServiceForBrowse    interface{} `json:"use_reranker_service_for_browse"`
			UseRerankerServiceForAll       interface{} `json:"use_reranker_service_for_all"`
			CustomAutosuggestUI            interface{} `json:"custom_autosuggest_ui"`
		} `json:"feature_variants"`
		SearchandizedItems struct {
		} `json:"searchandized_items"`
	} `json:"request"`
}

type PageData struct {
	Request struct {
		Page              int `json:"page"`
		NumResultsPerPage int `json:"num_results_per_page"`
		FmtOptions        struct {
			GroupsMaxDepth      int      `json:"groups_max_depth"`
			GroupsStart         string   `json:"groups_start"`
			ShowHiddenFields    bool     `json:"show_hidden_fields"`
			HiddenFields        []string `json:"hidden_fields"`
			ShowHiddenFacets    bool     `json:"show_hidden_facets"`
			HiddenFacets        []string `json:"hidden_facets"`
			ShowProtectedFacets bool     `json:"show_protected_facets"`
		} `json:"fmt_options"`
		SortBy         string `json:"sort_by"`
		SortOrder      string `json:"sort_order"`
		BlacklistRules bool   `json:"blacklist_rules"`
		Term           string `json:"term"`
		Section        string `json:"section"`
		Features       struct {
			QueryItems                     bool `json:"query_items"`
			AATest                         bool `json:"a_a_test"`
			AutoGeneratedRefinedQueryRules bool `json:"auto_generated_refined_query_rules"`
			ManualSearchandizing           bool `json:"manual_searchandizing"`
			Personalization                bool `json:"personalization"`
			FilterItems                    bool `json:"filter_items"`
			UseRerankerServiceForSearch    bool `json:"use_reranker_service_for_search"`
			UseRerankerServiceForBrowse    bool `json:"use_reranker_service_for_browse"`
			UseRerankerServiceForAll       bool `json:"use_reranker_service_for_all"`
			CustomAutosuggestUI            bool `json:"custom_autosuggest_ui"`
		} `json:"features"`
		FeatureVariants struct {
			QueryItems                     string      `json:"query_items"`
			AATest                         interface{} `json:"a_a_test"`
			AutoGeneratedRefinedQueryRules string      `json:"auto_generated_refined_query_rules"`
			ManualSearchandizing           interface{} `json:"manual_searchandizing"`
			Personalization                string      `json:"personalization"`
			FilterItems                    string      `json:"filter_items"`
			UseRerankerServiceForSearch    interface{} `json:"use_reranker_service_for_search"`
			UseRerankerServiceForBrowse    interface{} `json:"use_reranker_service_for_browse"`
			UseRerankerServiceForAll       interface{} `json:"use_reranker_service_for_all"`
			CustomAutosuggestUI            interface{} `json:"custom_autosuggest_ui"`
		} `json:"feature_variants"`
		SearchandizedItems struct {
		} `json:"searchandized_items"`
	} `json:"request"`
	Response struct {
		ResultSources struct {
			TokenMatch struct {
				Count int `json:"count"`
			} `json:"token_match"`
			EmbeddingsMatch struct {
				Count int `json:"count"`
			} `json:"embeddings_match"`
		} `json:"result_sources"`
		Facets []struct {
			DisplayName string `json:"display_name"`
			Name        string `json:"name"`
			Type        string `json:"type"`
			Options     []struct {
				Status      string `json:"status"`
				Count       int    `json:"count"`
				DisplayName string `json:"display_name"`
				Value       string `json:"value"`
				Data        struct {
					Year          string `json:"year"`
					Location      string `json:"location"`
					MobileDisplay bool   `json:"mobile_display"`
				} `json:"data"`
			} `json:"options,omitempty"`
			Hidden bool `json:"hidden"`
			Data   struct {
			} `json:"data"`
			Status struct {
			} `json:"status,omitempty"`
			Min int `json:"min,omitempty"`
			Max int `json:"max,omitempty"`
		} `json:"facets"`
		Groups []struct {
			GroupID     string `json:"group_id"`
			DisplayName string `json:"display_name"`
			Count       int    `json:"count"`
			Data        struct {
			} `json:"data"`
			Children []struct {
				GroupID     string `json:"group_id"`
				DisplayName string `json:"display_name"`
				Count       int    `json:"count"`
				Data        struct {
				} `json:"data"`
				Children []interface{} `json:"children"`
				Parents  []struct {
					DisplayName string `json:"display_name"`
					GroupID     string `json:"group_id"`
				} `json:"parents"`
			} `json:"children"`
			Parents []interface{} `json:"parents"`
		} `json:"groups"`
		Results []struct {
			MatchedTerms []string `json:"matched_terms"`
			Data         struct {
				ID                             string `json:"id"`
				Sku                            string `json:"sku"`
				Slug                           string `json:"slug"`
				Color                          string `json:"color"`
				Category                       string `json:"category"`
				ImageURL                       string `json:"image_url"`
				ReleaseDate                    int    `json:"release_date"`
				ProductType                    string `json:"product_type"`
				ReleaseDateYear                int    `json:"release_date_year"`
				RetailPriceCents               int    `json:"retail_price_cents"`
				RetailPriceCentsEur            int    `json:"retail_price_cents_eur"`
				RetailPriceCentsGbp            int    `json:"retail_price_cents_gbp"`
				RetailPriceCentsAud            int    `json:"retail_price_cents_aud"`
				RetailPriceCentsKrw            int    `json:"retail_price_cents_krw"`
				RetailPriceCentsJpy            int    `json:"retail_price_cents_jpy"`
				RetailPriceCentsCad            int    `json:"retail_price_cents_cad"`
				RetailPriceCentsSgd            int    `json:"retail_price_cents_sgd"`
				RetailPriceCentsTwd            int    `json:"retail_price_cents_twd"`
				RetailPriceCentsCny            int    `json:"retail_price_cents_cny"`
				RetailPriceCentsMyr            int    `json:"retail_price_cents_myr"`
				RetailPriceCentsHkd            int    `json:"retail_price_cents_hkd"`
				VariationID                    string `json:"variation_id"`
				UsedImageURL                   string `json:"used_image_url"`
				CheapestProduct                string `json:"cheapest_product"`
				ProductCondition               string `json:"product_condition"`
				LowestPriceCents               int    `json:"lowest_price_cents"`
				LowestPriceCentsTwd            int    `json:"lowest_price_cents_twd"`
				LowestPriceCentsMyr            int    `json:"lowest_price_cents_myr"`
				LowestPriceCentsHkd            int    `json:"lowest_price_cents_hkd"`
				LowestPriceCentsCad            int    `json:"lowest_price_cents_cad"`
				LowestPriceCentsCny            int    `json:"lowest_price_cents_cny"`
				LowestPriceCentsAud            int    `json:"lowest_price_cents_aud"`
				LowestPriceCentsGbp            int    `json:"lowest_price_cents_gbp"`
				LowestPriceCentsSgd            int    `json:"lowest_price_cents_sgd"`
				LowestPriceCentsKrw            int    `json:"lowest_price_cents_krw"`
				LowestPriceCentsEur            int    `json:"lowest_price_cents_eur"`
				LowestPriceCentsJpy            int    `json:"lowest_price_cents_jpy"`
				CountForProductCondition       int    `json:"count_for_product_condition"`
				InstantShipLowestPriceCents    int    `json:"instant_ship_lowest_price_cents"`
				InstantShipLowestPriceCentsCny int    `json:"instant_ship_lowest_price_cents_cny"`
				InstantShipLowestPriceCentsKrw int    `json:"instant_ship_lowest_price_cents_krw"`
				InstantShipLowestPriceCentsTwd int    `json:"instant_ship_lowest_price_cents_twd"`
				InstantShipLowestPriceCentsCad int    `json:"instant_ship_lowest_price_cents_cad"`
				InstantShipLowestPriceCentsHkd int    `json:"instant_ship_lowest_price_cents_hkd"`
				InstantShipLowestPriceCentsEur int    `json:"instant_ship_lowest_price_cents_eur"`
				InstantShipLowestPriceCentsSgd int    `json:"instant_ship_lowest_price_cents_sgd"`
				InstantShipLowestPriceCentsGbp int    `json:"instant_ship_lowest_price_cents_gbp"`
				InstantShipLowestPriceCentsAud int    `json:"instant_ship_lowest_price_cents_aud"`
				InstantShipLowestPriceCentsMyr int    `json:"instant_ship_lowest_price_cents_myr"`
				InstantShipLowestPriceCentsJpy int    `json:"instant_ship_lowest_price_cents_jpy"`
				GpLowestPriceCents3            int    `json:"gp_lowest_price_cents_3"`
				GpInstantShipLowestPriceCents3 int    `json:"gp_instant_ship_lowest_price_cents_3"`
			} `json:"data"`
			Value     string `json:"value"`
			IsSlotted bool   `json:"is_slotted"`
			Labels    struct {
			} `json:"labels"`
		} `json:"results"`
		SortOptions []struct {
			SortBy      string `json:"sort_by"`
			DisplayName string `json:"display_name"`
			SortOrder   string `json:"sort_order"`
			Status      string `json:"status"`
		} `json:"sort_options"`
		RefinedContent  []interface{} `json:"refined_content"`
		TotalNumResults int           `json:"total_num_results"`
		Features        []struct {
			FeatureName string      `json:"feature_name"`
			DisplayName string      `json:"display_name"`
			Enabled     bool        `json:"enabled"`
			Variant     interface{} `json:"variant"`
		} `json:"features"`
	} `json:"response"`
	ResultID string `json:"result_id"`
}
